### ISSUE TITLE
Clean-up/revamp RTstats

### ISSUE THREAD

**Issue by dopplershift** [Unidata/unidata-usercomm#2]

**Comment by akrherz** [comment]
Sweet, thanks for opening this issue.  Please assign it to me and set the milestone to spring 2017 meeting as I don't appear to have that power.  I will detail out my implementation thoughts for comment soon.

**Comment by akrherz** [comment]
[rtstats](http://rtstats.unidata.ucar.edu) is a wonderful service provided by Unidata to help IDD members monitor their LDM feed volumes and latency.  This service runs on a server at Unidata and does the following (known to me) functions:

- runs a LDM accepting EXP rtstats products from the world
- processes these rtstat files into netcdf files that store the data
- has various cron scripts that do maintenance on these netcdf files
- has a manually produced/maintained table of IP/hostnames to lat/lons for spatial plotting
- has a website that provides various GEMPAK based visualizations of the data

Most of the code that does the above is very old and needs to be replaced/updated with modern tooling that does not rely on GEMPAK.  So I volunteered at the fall 2016 Unidata usercomm meeting to lead an effort to revamp the rtstats service and provide some enhanced functionality that would hopefully benefit the community.

My initial implementation thoughts are:

- Process the raw rtstats files into a PostgreSQL backend and remove netcdf usage
- create matplotlib scripts that directly replicate the current website functionality and maintain current URIs (this would not be a major effort and could be eliminated later if OK by community)
- use [GeoIP](https://www.maxmind.com/en/geoip-demo) to do IP to lat/lon conversion, perhaps there are better / more Free alternatives?
- https only for the website with letsencrpyt

If I can produce successful results for the initial implementation, a solicitation would be sent out on the `ldm-users` email list informing them of this work and asking for comments/ideas for new tooling they would like to see.  My initial idea on new services includes:

- create JSON(P) emitting web services that would provide stats back to the community /  drive new interactive webapps
- create interactive / javascript web browser based plotting tools that use the above web services
- create a web service that would emit data suitable for various monitoring packages, like nagios to consume.  This would allow sites to point their local monitoring at this service and set up alerting for when necessary.  (This idea is somewhat vague and may be dumped later...)
- create a dashboard for Unidata to monitor the health of the IDD
- create a dashboard for local sites to monitor their deployment

Currently, rtstats runs on a physical host with some SSD drives to help it handle the load.  The goal would be to move this to a VM and not need the speed of SSDs to make things work.  I would like this VM to run RHEL/centos 7.

So my initial tasks are:

- [ ] contact Unidata to request a LDM feed from their rtstats system
- [ ] define a schema and create a python parser to dump data into the database
- [ ] create matplotlib based replacements of the current website plots
- [ ] create PHP(?) based replacements of the HTML summary pages

At the moment I will be doing this work in my [rtstats git repo](https://github.com/akrherz/rtstats/).  I am curious to see how many pain will be found with the initial tasks and that will likely dictate how much excitement I have with adding new services.

Comments and offers to help are welcome!

**Comment by vgensini** [comment]
Daryl,

Sounds great! That would be a fantastic contribution. 

I am willing to assist in the git repo, especially for task three. I would like to see matplotlib/plotly used to make interactive maps that play nice with your JavaScript. 

Best,

--
Dr. Vittorio (Victor) A. Gensini
Associate Professor
Meteorology
College of DuPage
425 Fawell Blvd.
Glen Ellyn, IL 60137
Office: Berg Instructional Center 3503
ph: +1 (630) 942-3496 
http://weather.cod.edu/~vgensini

**Comment by dopplershift** [comment]
Everyone should have write access now so that you can close issues, label, etc.

**Comment by akrherz** [comment]
Thanks @dopplershift for the perms update.

So to provide folks an update on my initial progress...

- Unidata (@tyoksas) kindly set me up with a LDM feed of their rtstats and sent along a tarball of the current code base.
- I have established a preliminary database schema and python ingest process that are both performing at reasonable levels.  (My SSD laptop is at 15% CPU with about 4% iowait).
- Currently, my ingest processes about 18,000 data points per minute.  A data point being the combination of a LDM host reporting stats from one upstream origin and from one feedtype.

So I should not be too many days away from providing folks with a test website to play with and so we can iterate further on this.  To get appetites wet, here's a fun report of the number of hosts reporting a given LDM version based on data for the past hour or so.

```sql
with data as (
  select distinct p.node_hostname, r.version
  from ldm_rtstats r JOIN ldm_feedtype_paths p on (r.feedtype_path = p.id)
)
select v.version, count(*) from ldm_versions v JOIN data d on (v.id = d.version)
GROUP by v.version ORDER by count DESC;
  version   | count 
------------+-------
 6.12.14    |   103
 6.11.6     |    40
 6.8.1      |    36
 6.13.3     |    35
 6.10.1     |    35
 6.13.4     |    32
 6.12.6     |    27
 6.11.7     |    22
 6.6.5      |    20
 6.9.8      |    17
 6.7.0      |    14
 6.12.9     |    13
 6.11.2     |    11
 6.13.1     |     9
 6.11.1     |     8
 6.13.2     |     7
 6.9.7      |     7
 6.12.3     |     6
 6.8.0      |     6
 6.12.4     |     6
 6.11.5     |     5
 6.13.0     |     4
 6.13.5.2   |     4
 6.7.1      |     3
 6.12.7     |     2
 6.11.0     |     2
 6.3.0      |     2
 6.4.5      |     2
 6.6.2      |     1
 6.0.14     |     1
 6.12.7.208 |     1
 6.12.15.28 |     1
 6.9.5      |     1
 6.12.13    |     1
 6.4.2      |     1
 6.13.4.3   |     1


```

**Comment by akrherz** [comment]
Work is progressing nicely, but there is a significant limitation that I could use some community feedback on.

The LDM rtstats program had a BUG that was fixed [here](https://github.com/Unidata/LDM/commit/5f98374b080cae1d401e7d7b1a65333d9d3f6995#diff-2e6aea29d0c100636db1c7aeb46ae54d).  This bug caused the origin field to be truncated at 32 bytes.  So for example, instead of having this `chico.unidata.ucar.edu_v_idd.unidata.ucar.edu` as the origin field, it would be truncated to this `chico.unidata.ucar.edu_v_idd.uni`

I believe BUG was introduced [here](https://github.com/Unidata/LDM/commit/2f4f2d97f22db7e74fbd959f8b5b7ded5fffbd60), so it impacts LDM versions 6.11.7 through 6.12.15.38

Currently, whenever I encounter a 32 byte origin field, I am completely ignoring the rtstat report :(  I will likely add an additional LDM version check to only exclude those in the case of the LDM version also matching the above range (see @akrherz/rtstats#1).  I am unsure if I am clever enough to add heuristics to attempt to guess the truncated portion of the origin string. 

Does the community have thoughts on what I should do here?  Perhaps I could just drop the second portion of the origin and simply make a null of the upstream source and keep the originator.  This would get hairy and likely create some incorrect reports.

**Comment by semmerson** [comment]
@akrherz I'd say what to do depends on what you're trying to do, i.e., how the subsequent origin field will be used.

In any case, this problem should eventually become moot as people upgrade their LDM.

**Comment by akrherz** [comment]
Thanks @semmerson , I think my primary goal is to provide accurate stats, so if there is ambiguity with the upstream field, I might as well ignore it for now.  Hopefully when folks see the revamped rtstats site, it will be a juicy carrot to prod them to upgrade...

So work continues and my initial demonstration website is not far away from sharing, but I have another question for the community to consider.  Here's a report for the number of 'data points' in the database for the past hour, grouped by feedtype

```sql
 select 
(select feedtype from ldm_feedtypes where id = p.feedtype_id) as feedtype, count(*) 
from ldm_rtstats r JOIN ldm_feedtype_paths p on (r.feedtype_path_id = p.id) 
where r.entry_added > '2016-10-07 12:17+00' GROUP by feedtype ORDER by count DESC;
  feedtype  | count  
------------+--------
 NEXRAD2    | 633109
 IDS|DDPLUS |  43039
 HDS        |  25728
 EXP        |  21411
 NEXRAD3    |  21125
 NGRID      |  12801
 NOTHER     |  12642
 NIMAGE     |   8160
 LIGHTNING  |   6935
 FNEXRAD    |   4070
 CONDUIT    |   3143
 FSL2       |   2531
 UNIWISC    |   2397
 NNEXRAD    |   1868
 WMO        |   1252
 FSL4       |   1171
 WSI        |    901
 FSL5       |    651
 FSL3       |    543
 PCWS       |    352
 SPARE      |    242
 NGRAPH     |    176
 GPSSRC     |    112
 NLDN       |    108
 NTEXT      |     63
 GPS        |     29
 PPS        |     15
(27 rows)
```

So NEXRAD2 dominates the number of entries!  This is because each RADAR site shows up as an LDM product originator and so the ldm_feedtype_paths explodes for each host feeding data.  For instance, my NEXRAD2 only host has 15,523 entries for this one hour period.  This creates unmitigated plotting disasters, like currently [here](http://rtstats.unidata.ucar.edu/cgi-bin/rtstats/iddstats_nc?NEXRAD2+level2-dc.agron.iastate.edu). My initial thought is to aggregate these results up for downstream hosts of the top tier CRAFT sites.  So while the top tier sites would retain these detailed stats, the downstream hosts would only see the top tier CRAFT site as the product origin.  Perhaps this is not a big enough issue to fuss with?  The reason I am currently down this path is that one of my JSON webservices is currently emitting 18 MB response for a test host. I am tracking this issue akrherz/rtstats#3 and hoping for some community feedback.

**Comment by akrherz** [comment]
After ruminating on the aforementioned NEXRAD2 feedtype issue, I have currently implemented an aggregation whereby I ignore the origin host and simply set the origin to the relay host.  This change will likely need to be revisited or perhaps some manual hacks added for the top tier CRAFT hosts to more properly account for individual NEXRAD latency.  Anyway, here's a comparison of this change

| current rtstats | work in progress |
| ----------------- | --------------------- |
| ![old](https://cloud.githubusercontent.com/assets/210858/19375339/a8bbf0f2-9198-11e6-8204-0c4d9db4d5e9.gif) | ![new](https://cloud.githubusercontent.com/assets/210858/19375342/af7eb708-9198-11e6-9036-fb79cdef80d5.png) |

PS and in case you are curious, the new plot shows `metfs1.agron.iastate.edu` as a NEXRAD2 source, which is right as it originates a University RADAR.

PSS, the current plot does not do stacked values and the new one does, which I think is more proper in this instance.

Anyway, feedback is always welcome on this aggregation method.  Once I get some performance issues resolved, I'll pass around the demonstration website for comments.

**Comment by semmerson** [comment]
The current volume plots sort the contribution from largest (at the bottom)
to least (at the top) for each bin -- which makes it easy to note when the
relative contribution changes but can be distracting. The new one sorts by
source, which appears less distracting.

Which is better?

Regards,
Steve Emmerson


Regards,
Steve Emmerson

**Comment by akrherz** [comment]
Uh oh, four weeks, without an update, sorry.  I believe I completed an initial task of replicating all current rtstats website functionality and replicated all current URIs.  You can see the result here.

    https://rtstats.agron.iastate.edu

I am still having some database performance issues that may some parts of the website very slow.  The virtual machine this service runs on is rather busy and doesn't have the IOPS available to make it work better (lame excuse) or to allocate more memory to the instance.  I have some ideas and perhaps having more eyeballs on the website will shame me into figuring out the issues more quickly!

The addition of more tools and options will come as time permits and ideas are submitted.  I also need to seek 'approval', that the solution I have come up with is something Unidata will use to replace their current service.  I don't have the intention of running my own rtstats website :)  I will add some more system / install documentation and put a bow on it for Unidata's sysadmin / rtstats folks approval.

**Comment by m1schmidt** [comment]
We can put it up on a system here when you're ready to have a faster
machine crunch the data and the have documentation available -- no need for
gift wrap...
I do see a "color" issue with the "Cumulative volume summary graph" as seen
below.  Very nice work, thanks.

[image: Inline image 1]

**Comment by akrherz** [comment]
Thanks for your kind words @m1schmidt , so to address your comments

1. I have reviewed my install procedure and just now ran through it on a minimal RHEL 7.3 server install. It worked better than most things I do, so I am a bit nervous.  Anyway, the [repo's README](https://github.com/akrherz/rtstats) as the details.
2. Your image example did not come through properly, but I found what you are saying.  I'll fix it eventually and it is tracked at akrherz/rtstats#4

Perhaps the rtstats repo needs to move up to the Unidata organization at this point?  Up to you folks. Would be certainly happy to take PRs or whatever desired.

**Comment by akrherz** [comment]
[Spammed ldm-users email list](http://www.unidata.ucar.edu/mailing_lists/archives/ldm-users/2017/msg00045.html) denoting what trouble I am up to

**Comment by akrherz** [comment]
Hi @m1schmidt , we gonna take a swing at some implementation at Unidata prior to UserComm? :)  Maybe if at least some hardware was allocated and available prior to the meeting, we could sit together and hammer out the install in hopefully not too long of time?

**Comment by m1schmidt** [comment]
We'll work on making it happen.

mike

**Comment by akrherz** [comment]
Thanks to @m1schmidt , we have the initial implementation running at Unidata and my github repo was migrated to the Unidata organization here.

http://rtstatstest.unidata.ucar.edu

Some quirks were found with the install documentation at Unidata and are being tracked Unidata/rtstats#8 , so am closing this ticket here and will continue to contribute to the Unidata/rtstats repo.  Thanks all!
